# See https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates
version: 2

multi-ecosystem-groups:
  all-dependencies:
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "all-dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "all-dependencies"

  - package-ecosystem: "npm"
    directory: "/web"
    patterns: ["*"]
    multi-ecosystem-group: "all-dependencies"
