version: "2"

run:
    timeout: 5m
    tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - bidichk
    - contextcheck
    - ineffassign
    - gocyclo
  settings:
    gocyclo:
      min-complexity: 10