version: "2"

run:
    timeout: 5m
    tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - bidichk
    - contextcheck
    - ineffassign
    - gocyclo

linters-settings:
  gocyclo:
    min-complexity: 10