version: "2"

run:
    timeout: 5m
    tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - bidichk
    - contextcheck
    - ineffassign
    - gocyclo
  settings:
    gocyclo:
      min-complexity: 10
  exclusions:
    rules:
      - path: _test\.go$
        linters: [gocyclo]
      - path: cmd/server/main\.go$
        linters: [gocyclo]
      - path: cmd/worker/main\.go$
        linters: [gocyclo]
      - path: cmd/configure/
        linters: [gocyclo]