# GoReleaser configuration for building cross-platform binaries
# Documentation: https://goreleaser.com
version: 2

before:
  hooks:
    # Clean up any previous builds
    - go mod tidy
    # Generate any required files (if needed)
    # - go generate ./...

builds:
  - id: "server"
    # Binary name for the API server
    binary: "server"

    # Entry point for the server application
    main: ./cmd/server

    # Target environments
    goos:
      - linux
      - windows
      - darwin

    goarch:
      - amd64
      - arm64

    # Environment variables for the build
    env:
      - CGO_ENABLED=0

    # Build flags
    flags:
      - -trimpath

    # Linker flags for smaller binaries and version info
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

  - id: "configure"
    # Binary name for the configure tool
    binary: "configure"

    # Entry point for the configure application
    main: ./cmd/configure

    # Target environments
    goos:
      - linux
      - windows
      - darwin

    goarch:
      - amd64
      - arm64

    # Environment variables for the build
    env:
      - CGO_ENABLED=0

    # Build flags
    flags:
      - -trimpath

    # Linker flags for smaller binaries and version info
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

  - id: "worker"
    # Binary name for the worker
    binary: "worker"

    # Entry point for the worker application
    main: ./cmd/worker

    # Target environments
    goos:
      - linux
      - windows
      - darwin

    goarch:
      - amd64
      - arm64

    # Environment variables for the build
    env:
      - CGO_ENABLED=0

    # Build flags
    flags:
      - -trimpath

    # Linker flags for smaller binaries and version info
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

archives:
  - id: "server"
    # Archive name template for server binary
    name_template: >-
      {{ .ProjectName }}-server_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    # Files to include in archives
    files:
      - README.md
      - LICENSE
    builds:
      - server

  - id: "configure"
    # Archive name template for configure binary
    name_template: >-
      {{ .ProjectName }}-configure_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    # Files to include in archives
    files:
      - README.md
      - LICENSE
    builds:
      - configure

  - id: "worker"
    # Archive name template for worker binary
    name_template: >-
      {{ .ProjectName }}-worker_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

    # Files to include in archives
    files:
      - README.md
      - LICENSE
    builds:
      - worker

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "^style:"
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999

# GitHub release configuration
release:
  # Create a draft release
  draft: false

  # Mark as pre-release if version contains pre-release identifiers
  prerelease: auto

  # Release name template
  name_template: "Release {{.Version}}"

  # Release body template
  header: |
    ## Release {{.Version}}

    Welcome to this new release!

# Docker images
# Note: Dockerfiles build binaries themselves, so GoReleaser's pre-built binaries are not used
dockers:
  # Server image (includes server and configure binaries)
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}-server:{{ .Version }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}-server:latest"
    dockerfile: server.Dockerfile
    use: docker
    # The Dockerfile copies everything with COPY . ., so extra_files are optional
    # but listed here for clarity about what's included in the build context
    extra_files:
      - go.mod
      - go.sum
      - README.md
      - LICENSE
      - cmd/
      - internal/
      - api/
      - scripts/
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}-server"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

  # Worker image
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}-worker:{{ .Version }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}-worker:latest"
    dockerfile: worker.Dockerfile
    use: docker
    extra_files:
      - go.mod
      - go.sum
      - README.md
      - LICENSE
      - cmd/
      - internal/
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}-worker"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

  # Web frontend image
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}-web:{{ .Version }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}-web:latest"
    dockerfile: web.Dockerfile
    use: docker
    extra_files:
      - web/
      - scripts/generate_config.sh
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}-web"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

# Homebrew tap (optional - uncomment if you want Homebrew formula)
# brews:
#   - repository:
#       owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
#       name: homebrew-tap
#     folder: Formula
#     homepage: "https://github.com/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}"
#     description: "Description of your project"
#     license: "MIT"
